#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket;
use Data::Dumper;
use threads;
use threads::shared;

$| = 0;
our @clients;
share(@clients);
@clients = ();

# create the server socket
my $sock = new IO::Socket::INET (
    LocalPort => '31337',
    Proto => 'tcp',
    Listen => 1,
    Reuse => 1,
);

sub handle_client { 
    my $c = shift;
    print $c "001 - Nickname\n";
    my $line = <$c>;
    $line =~ s/\r//;
    $line =~ s/\n//;
    print "Got Nickname '$line' (" , $c->peerhost(), ")\n";
    for my $client (@clients) { 
        open my $fh, ">&=$client" or warn $! and die;
        print $fh  "-> $line connected\n";
        close($fh);
    }
    while (my $input = $c->getline()) {
        if ($input =~ m/^\/names.*/) {
            $c->say("list of names");
        }
        else {
            for my $client (@clients) { 
                open my $fh, ">&=$client" or warn $! and die;
                print $fh  "$input";
                close($fh);
            }
        }
    }
}

while(my $client = $sock->accept()) {
    push (@clients, fileno $client);
    my $thr = threads->new( \&handle_client, $client )->detach();
}
