#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket;
use Data::Dumper;
use threads;
use threads::shared;

$| = 0;
our @clients;
share(@clients);
@clients = ();

our @client_names;
share(@client_names);
@client_names = ();

# create the server socket
my $sock = new IO::Socket::INET (
    LocalPort => '31337',
    Proto => 'tcp',
    Listen => 1,
    Reuse => 1,
);

sub handle_client { 
    my $c = shift;
    print $c "001 - Nickname\n";
    my $line = <$c>;
    $line =~ s/\r//;
    $line =~ s/\n//;
    print "Got Nickname '$line' (" , $c->peerhost(), ")\n";
    $client_names[fileno $c] = $line;
    for my $client (@clients) { 
        open my $fh, ">&=$client" or warn $! and (($client_names[$client] = undef) and next);
        print $fh  "-> $line connected (", $c->peerhost , ")\n";
        close($fh);
    }
    while (my $input = $c->getline()) {
        if ($input =~ m/^\/names.*/) {
            my $namelist;
            for (@client_names) {
                if (defined $_) {
                    $namelist .= " $_ ";
                }
            }
            $c->say($namelist);
        }
        else {
            for my $client (@clients) { 
                if (open my $fh, ">&=$client") {
                    print $fh  "$input";
                    close($fh);
                }
                else {
                    $client_names[$client] = undef;
                    next;
                }
            }
        }
    }
}

my %thrds;

while(my $client = $sock->accept()) {
    push (@clients, fileno $client);
    $thrds{fileno $client} = threads->new( \&handle_client, $client )->detach();
    for (keys %thrds) {
        unless ($thrds{$_}) {
            delete $thrds{$_};
            $client_names[$_] = undef;
        }
    }
}
