#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket;
use Data::Dumper;
use threads;
use threads::shared;

$| = 0;
our @clients;
share(@clients);
@clients = ();

# create the server socket
my $sock = new IO::Socket::INET (
    LocalPort => '31337',
    Proto => 'tcp',
    Listen => 1,
    Reuse => 1,
);

sub handle_client { 
    my $c = shift;
    print $c "Nickname: ";
    my $line = <$c>;
    $line =~ s/\r//;
    $line =~ s/\n//;
    print "Got Nickname '$line' (" , $c->peerhost(), ")\n";
    while (my $input = $c->getline()) {
        for my $client (@clients) { 
            open my $fh, ">&=$client" or warn $! and die;
            print $fh  "$input";
            print "$input";
            close($fh);
        }
    }
}

while(my $client = $sock->accept()) {
    push (@clients, fileno $client);
    my $thr = threads->new( \&handle_client, $client )->detach();
}
